# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 22:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180505_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='main_photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 15, 19, 23, 370980)),
        ),
    ]
