# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180505_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='enterprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Enterprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 15, 33, 44, 763311)),
        ),
    ]
