# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180505_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 17, 15, 23, 666215)),
        ),
        migrations.AlterField(
            model_name='post',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Enterprise'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(max_length=200, null=True, upload_to=''),
        ),
    ]
