# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180505_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 17, 17, 38, 497313)),
        ),
    ]
