# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180505_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 17, 57, 44, 700555)),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.URLField(null=True),
        ),
    ]
