# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180505_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 18, 46, 29, 721917)),
        ),
        migrations.AlterField(
            model_name='post',
            name='external_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
