# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180505_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='hashtag',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 19, 42, 19, 807320)),
        ),
    ]
