# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180505_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 6, 4, 35, 864110)),
        ),
    ]
